name: PR CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-test-and-check-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.5.0
        poetry install -E visualisation

    - name: Ensure Linted
      run: |
        poetry run make ci-lint

    - name: Run Coverage
      run: |
        poetry run make coverage
